### ISSUE TITLE
Erro Authentication

### ISSUE THREAD

**Issue by samuelcarrarap** [ianneub/php_backup_s3#7]
Warning: S3::getBucket(): [InvalidRequest] The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

**Comment by ianneub** [comment]
Thanks for the report @samuelcarrarap . I'm sorry, but I am not maintaining this repository anymore. If you'd like to contribute a pull request that fixes the issue I'd be happy to merge it! Please see some other options in the readme if you want to find another project.
